### ISSUE TITLE
Modifying MirrorBERT to create MirrorWiC

### ISSUE THREAD

**Issue by daniel347x** [cambridgeltl/MirrorWiC#1]
Thanks so much for the exciting papers re. MirrorBERT and MirrorWiC!

Since this code isn't available yet, I took a look at MirrorBERT, and I think MirrorWiC can be created by simply modifying a single function in MirrorBERT:

`erase_and_mask()`
https://github.com/cambridgeltl/mirror-bert/blob/main/src/data_loader.py#L15

If you get a chance, could you confirm?

Thanks!

**Comment by qianchu** [comment]
Hi, 
Thanks for your interest. Apart from the hyper-parameters in erase_and_mask, dropout rate and etc, the architecture of MirrorWiC is different from Mirrorbert as MirrorWiC trains the word-in-context representation rather than the CLS or mean pooling.  I will release the code within a couple of weeks. 

Thanks!

**Comment by daniel347x** [comment]
Great! Thanks so much! Yes, performing the loss against the word-in-context output embedding fits exactly this paradigm. It makes intuitive sense and the results from your paper, particularly Fig. 2 (g)-(h), are very remarkable. I hope the paper gets a lot of traction.

**Comment by qianchu** [comment]
Thank you! I will try releasing the code as soon as possible:)

**Comment by hardyqr** [comment]
@daniel347x Hey Daniel, the code is now released. The core component can be seen here: https://github.com/cambridgeltl/MirrorWiC/blob/933ea0bf2ef3f18868bd87b92a5052ba42306f01/train_scripts/src/metric_learning.py#L131
